version: '3.8'
services:
   postgres_db:
      image: postgres:latest
      container_name: pgdb 
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      ports:
      - '5432:5432'
      volumes:
      - ./pgdata:/var/lib/postgresql/data
