version: '3.8'
services:
   postgres_db:
      image: postgres:bullseye
      container_name: pgdb 
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      ports:
      - '5432:5432'
      volumes:
      - ./pg-data:/var/lib/postgresql/data

   pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
      - "8081:80"
      environment:
         PGADMIN_DEFAULT_EMAIL: pgadmin@nikolaidan.altostrat.com
         PGADMIN_DEFAULT_PASSWORD: postgres
      volumes:
      - ./pgadmin-data:/var/lib/pgadmin